/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Brand {
  'id' : bigint,
  'mapsUrl' : string,
  'published' : boolean,
  'name' : string,
  'description' : string,
  'category' : string,
  'location' : string,
}
export interface BrandInput {
  'mapsUrl' : string,
  'name' : string,
  'description' : string,
  'category' : string,
  'location' : string,
}
export interface ContactEnquiry {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface FAQInput { 'question' : string, 'answer' : string }
export interface FAQItem {
  'id' : bigint,
  'question' : string,
  'published' : boolean,
  'answer' : string,
}
export interface FullPricingPlan {
  'id' : bigint,
  'hasSeasonOffer' : boolean,
  'videoCount' : bigint,
  'name' : string,
  'offerDescription' : string,
  'deliveryDays' : bigint,
  'enabled' : boolean,
  'offerPrice' : bigint,
  'price' : bigint,
  'planTypeBadge' : string,
  'services' : Array<string>,
}
export interface FullPricingPlanInput {
  'hasSeasonOffer' : boolean,
  'videoCount' : bigint,
  'name' : string,
  'offerDescription' : string,
  'deliveryDays' : bigint,
  'enabled' : boolean,
  'offerPrice' : bigint,
  'price' : bigint,
  'planTypeBadge' : string,
  'services' : Array<string>,
}
export interface MonthlyPackage {
  'videoCount' : bigint,
  'description' : string,
  'enabled' : boolean,
  'price' : bigint,
}
export interface OfficeProfile {
  'city' : string,
  'mapsUrl' : string,
  'whatsapp' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface PageContent {
  'heroSubtitle' : string,
  'sections' : Array<PageSection>,
  'heroTitle' : string,
  'heroBackgroundImage' : string,
  'pageId' : string,
}
export interface PageSection {
  'id' : string,
  'description' : string,
  'heading' : string,
  'imageUrl' : string,
  'visible' : boolean,
}
export interface PortfolioVideo {
  'id' : bigint,
  'title' : string,
  'vimeoId' : string,
  'published' : boolean,
  'description' : string,
  'category' : string,
}
export interface PortfolioVideoFullInput {
  'id' : bigint,
  'title' : string,
  'vimeoId' : string,
  'published' : boolean,
  'description' : string,
  'category' : string,
}
export interface PresetPackage {
  'id' : bigint,
  'features' : Array<string>,
  'name' : string,
  'deliveryDays' : bigint,
  'enabled' : boolean,
  'price' : bigint,
}
export interface PricingPlan {
  'id' : bigint,
  'planLabel' : string,
  'published' : boolean,
  'note' : string,
  'price' : bigint,
}
export interface PricingPlanInput {
  'planLabel' : string,
  'note' : string,
  'price' : bigint,
}
export interface ReelPricing {
  'editingContentCamera' : bigint,
  'editingCamera' : bigint,
  'editingOnly' : bigint,
}
export interface SeasonOfferSettings {
  'title' : string,
  'endDate' : string,
  'postOfferMessage' : string,
  'discountAmount' : bigint,
  'applicablePlanIds' : Array<bigint>,
  'offerMessage' : string,
  'postOfferWindowDays' : bigint,
  'badgeColor' : string,
  'startDate' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'features' : Array<string>,
  'published' : boolean,
  'description' : string,
}
export interface ServiceFullInput {
  'id' : bigint,
  'title' : string,
  'features' : Array<string>,
  'description' : string,
}
export interface ServiceInput {
  'title' : string,
  'features' : Array<string>,
  'description' : string,
}
export interface SiteStats {
  'videosDelivered' : bigint,
  'happyClients' : bigint,
  'viewsGenerated' : bigint,
}
export interface SliderRates {
  'content' : bigint,
  'editing' : bigint,
  'other' : bigint,
  'videography' : bigint,
}
export interface Testimonial {
  'id' : bigint,
  'review' : string,
  'clientName' : string,
  'published' : boolean,
  'company' : string,
  'rating' : bigint,
}
export interface TestimonialFullInput {
  'id' : bigint,
  'review' : string,
  'clientName' : string,
  'published' : boolean,
  'company' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoInput {
  'title' : string,
  'vimeoId' : string,
  'description' : string,
  'category' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBrandPartner' : ActorMethod<[BrandInput], bigint>,
  'addFAQItem' : ActorMethod<[FAQInput], bigint>,
  'addFullPricingPlan' : ActorMethod<[FullPricingPlanInput], bigint>,
  'addPortfolioVideo' : ActorMethod<[VideoInput], bigint>,
  'addPricingPlan' : ActorMethod<[PricingPlanInput], bigint>,
  'addService' : ActorMethod<[ServiceInput], bigint>,
  'addTestimonial' : ActorMethod<[TestimonialFullInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBrandPartner' : ActorMethod<[bigint], undefined>,
  'deleteFAQItem' : ActorMethod<[bigint], undefined>,
  'deleteFullPricingPlan' : ActorMethod<[bigint], undefined>,
  'deletePortfolioVideo' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'fullPricingSeed' : ActorMethod<[], undefined>,
  'getAllBrands' : ActorMethod<[], Array<Brand>>,
  'getAllContactEnquiries' : ActorMethod<[], Array<ContactEnquiry>>,
  'getAllFAQs' : ActorMethod<[], Array<FAQItem>>,
  'getAllFullPricingPlans' : ActorMethod<[], Array<FullPricingPlan>>,
  'getAllPageContent' : ActorMethod<[], Array<[string, PageContent]>>,
  'getAllPresetPackages' : ActorMethod<[], Array<PresetPackage>>,
  'getAllPricingPlans' : ActorMethod<[], Array<PricingPlan>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAllVideos' : ActorMethod<[], Array<PortfolioVideo>>,
  'getBrandsByCategory' : ActorMethod<[string], Array<Brand>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEnabledFullPricingPlans' : ActorMethod<[], Array<FullPricingPlan>>,
  'getMonthlyPackage' : ActorMethod<[], MonthlyPackage>,
  'getOfficeProfile' : ActorMethod<[], OfficeProfile>,
  'getPageContent' : ActorMethod<[string], [] | [PageContent]>,
  'getPresetPackages' : ActorMethod<[], Array<PresetPackage>>,
  'getPublishedBrands' : ActorMethod<[], Array<Brand>>,
  'getPublishedFAQs' : ActorMethod<[], Array<FAQItem>>,
  'getPublishedPricingPlans' : ActorMethod<[], Array<PricingPlan>>,
  'getPublishedServices' : ActorMethod<[], Array<Service>>,
  'getPublishedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getPublishedVideos' : ActorMethod<[], Array<PortfolioVideo>>,
  'getReelPricing' : ActorMethod<[], ReelPricing>,
  'getSeasonOfferSettings' : ActorMethod<[], SeasonOfferSettings>,
  'getServicesAndPricing' : ActorMethod<
    [],
    { 'pricing' : Array<PricingPlan>, 'services' : Array<Service> }
  >,
  'getSiteStats' : ActorMethod<[], SiteStats>,
  'getSliderRates' : ActorMethod<[], SliderRates>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoById' : ActorMethod<[bigint], [] | [PortfolioVideo]>,
  'getVideosByCategory' : ActorMethod<[string], Array<PortfolioVideo>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publicCombinedVideosBrands' : ActorMethod<
    [],
    { 'brands' : Array<Brand>, 'videos' : Array<PortfolioVideo> }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'seedPageContent' : ActorMethod<[], undefined>,
  'submitContactEnquiry' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'toggleBrandPublished' : ActorMethod<[bigint], boolean>,
  'toggleFAQPublished' : ActorMethod<[bigint], boolean>,
  'toggleFullPricingPlanEnabled' : ActorMethod<[bigint], boolean>,
  'togglePricingPublished' : ActorMethod<[bigint], boolean>,
  'toggleServicePublished' : ActorMethod<[bigint], boolean>,
  'toggleTestimonialPublished' : ActorMethod<[bigint], boolean>,
  'toggleVideoPublished' : ActorMethod<[bigint], boolean>,
  'updateBrandPartner' : ActorMethod<[bigint, BrandInput], undefined>,
  'updateFullPricingPlan' : ActorMethod<
    [bigint, FullPricingPlanInput],
    undefined
  >,
  'updateMonthlyPackage' : ActorMethod<[MonthlyPackage], undefined>,
  'updateOfficeProfile' : ActorMethod<[OfficeProfile], undefined>,
  'updatePageContent' : ActorMethod<[string, PageContent], undefined>,
  'updatePortfolioVideo' : ActorMethod<[PortfolioVideoFullInput], undefined>,
  'updatePresetPackage' : ActorMethod<[PresetPackage], undefined>,
  'updatePricingPlan' : ActorMethod<[bigint, PricingPlanInput], undefined>,
  'updateReelPricing' : ActorMethod<[ReelPricing], undefined>,
  'updateSeasonOfferSettings' : ActorMethod<[SeasonOfferSettings], undefined>,
  'updateService' : ActorMethod<[ServiceFullInput], undefined>,
  'updateSiteStats' : ActorMethod<[SiteStats], undefined>,
  'updateSliderRates' : ActorMethod<[SliderRates], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];