/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Brand {
  'id' : bigint,
  'mapsUrl' : string,
  'published' : boolean,
  'name' : string,
  'description' : string,
  'category' : string,
  'location' : string,
}
export interface BrandInput {
  'mapsUrl' : string,
  'name' : string,
  'description' : string,
  'category' : string,
  'location' : string,
}
export interface ContactEnquiry {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface FAQInput { 'question' : string, 'answer' : string }
export interface FAQItem {
  'id' : bigint,
  'question' : string,
  'published' : boolean,
  'answer' : string,
}
export interface OfficeProfile {
  'city' : string,
  'mapsUrl' : string,
  'whatsapp' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface PortfolioVideo {
  'id' : bigint,
  'title' : string,
  'vimeoId' : string,
  'published' : boolean,
  'description' : string,
  'category' : string,
}
export interface PortfolioVideoFullInput {
  'id' : bigint,
  'title' : string,
  'vimeoId' : string,
  'published' : boolean,
  'description' : string,
  'category' : string,
}
export interface PricingPlan {
  'id' : bigint,
  'planLabel' : string,
  'published' : boolean,
  'note' : string,
  'price' : bigint,
}
export interface PricingPlanInput {
  'planLabel' : string,
  'note' : string,
  'price' : bigint,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'features' : Array<string>,
  'published' : boolean,
  'description' : string,
}
export interface ServiceFullInput {
  'id' : bigint,
  'title' : string,
  'features' : Array<string>,
  'description' : string,
}
export interface ServiceInput {
  'title' : string,
  'features' : Array<string>,
  'description' : string,
}
export interface Testimonial {
  'id' : bigint,
  'review' : string,
  'clientName' : string,
  'published' : boolean,
  'company' : string,
  'rating' : bigint,
}
export interface TestimonialFullInput {
  'id' : bigint,
  'review' : string,
  'clientName' : string,
  'published' : boolean,
  'company' : string,
  'rating' : bigint,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoInput {
  'title' : string,
  'vimeoId' : string,
  'description' : string,
  'category' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBrandPartner' : ActorMethod<[BrandInput], bigint>,
  'addFAQItem' : ActorMethod<[FAQInput], bigint>,
  'addPortfolioVideo' : ActorMethod<[VideoInput], bigint>,
  'addPricingPlan' : ActorMethod<[PricingPlanInput], bigint>,
  'addService' : ActorMethod<[ServiceInput], bigint>,
  'addTestimonial' : ActorMethod<[TestimonialFullInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContactEnquiries' : ActorMethod<[], Array<ContactEnquiry>>,
  'getAllVideos' : ActorMethod<[], Array<PortfolioVideo>>,
  'getBrandsByCategory' : ActorMethod<[string], Array<Brand>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOfficeProfile' : ActorMethod<[], OfficeProfile>,
  'getPublishedBrands' : ActorMethod<[], Array<Brand>>,
  'getPublishedFAQs' : ActorMethod<[], Array<FAQItem>>,
  'getPublishedPricingPlans' : ActorMethod<[], Array<PricingPlan>>,
  'getPublishedServices' : ActorMethod<[], Array<Service>>,
  'getPublishedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getPublishedVideos' : ActorMethod<[], Array<PortfolioVideo>>,
  'getServicesAndPricing' : ActorMethod<
    [],
    { 'pricing' : Array<PricingPlan>, 'services' : Array<Service> }
  >,
  'getVideoById' : ActorMethod<[bigint], [] | [PortfolioVideo]>,
  'getVideosByCategory' : ActorMethod<[string], Array<PortfolioVideo>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publicCombinedVideosBrands' : ActorMethod<
    [],
    { 'brands' : Array<Brand>, 'videos' : Array<PortfolioVideo> }
  >,
  'seedData' : ActorMethod<[], undefined>,
  'submitContactEnquiry' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'toggleBrandPublished' : ActorMethod<[bigint], boolean>,
  'toggleFAQPublished' : ActorMethod<[bigint], boolean>,
  'togglePricingPublished' : ActorMethod<[bigint], boolean>,
  'toggleServicePublished' : ActorMethod<[bigint], boolean>,
  'toggleTestimonialPublished' : ActorMethod<[bigint], boolean>,
  'toggleVideoPublished' : ActorMethod<[bigint], boolean>,
  'updateBrandPartner' : ActorMethod<[bigint, BrandInput], undefined>,
  'updateOfficeProfile' : ActorMethod<[OfficeProfile], undefined>,
  'updatePortfolioVideo' : ActorMethod<[PortfolioVideoFullInput], undefined>,
  'updatePricingPlan' : ActorMethod<[bigint, PricingPlanInput], undefined>,
  'updateService' : ActorMethod<[ServiceFullInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];