/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BrandInput = IDL.Record({
  'mapsUrl' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const FAQInput = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const VideoInput = IDL.Record({
  'title' : IDL.Text,
  'vimeoId' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const PricingPlanInput = IDL.Record({
  'planLabel' : IDL.Text,
  'note' : IDL.Text,
  'price' : IDL.Nat,
});
export const ServiceInput = IDL.Record({
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const TestimonialFullInput = IDL.Record({
  'id' : IDL.Nat,
  'review' : IDL.Text,
  'clientName' : IDL.Text,
  'published' : IDL.Bool,
  'company' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactEnquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const PortfolioVideo = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'vimeoId' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Brand = IDL.Record({
  'id' : IDL.Nat,
  'mapsUrl' : IDL.Text,
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const OfficeProfile = IDL.Record({
  'city' : IDL.Text,
  'mapsUrl' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const FAQItem = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'published' : IDL.Bool,
  'answer' : IDL.Text,
});
export const PricingPlan = IDL.Record({
  'id' : IDL.Nat,
  'planLabel' : IDL.Text,
  'published' : IDL.Bool,
  'note' : IDL.Text,
  'price' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'published' : IDL.Bool,
  'description' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'review' : IDL.Text,
  'clientName' : IDL.Text,
  'published' : IDL.Bool,
  'company' : IDL.Text,
  'rating' : IDL.Nat,
});
export const PortfolioVideoFullInput = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'vimeoId' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const ServiceFullInput = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBrandPartner' : IDL.Func([BrandInput], [IDL.Nat], []),
  'addFAQItem' : IDL.Func([FAQInput], [IDL.Nat], []),
  'addPortfolioVideo' : IDL.Func([VideoInput], [IDL.Nat], []),
  'addPricingPlan' : IDL.Func([PricingPlanInput], [IDL.Nat], []),
  'addService' : IDL.Func([ServiceInput], [IDL.Nat], []),
  'addTestimonial' : IDL.Func([TestimonialFullInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContactEnquiries' : IDL.Func([], [IDL.Vec(ContactEnquiry)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(PortfolioVideo)], ['query']),
  'getBrandsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Brand)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOfficeProfile' : IDL.Func([], [OfficeProfile], ['query']),
  'getPublishedBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getPublishedFAQs' : IDL.Func([], [IDL.Vec(FAQItem)], ['query']),
  'getPublishedPricingPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
  'getPublishedServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getPublishedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getPublishedVideos' : IDL.Func([], [IDL.Vec(PortfolioVideo)], ['query']),
  'getServicesAndPricing' : IDL.Func(
      [],
      [
        IDL.Record({
          'pricing' : IDL.Vec(PricingPlan),
          'services' : IDL.Vec(Service),
        }),
      ],
      ['query'],
    ),
  'getVideoById' : IDL.Func([IDL.Nat], [IDL.Opt(PortfolioVideo)], ['query']),
  'getVideosByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioVideo)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publicCombinedVideosBrands' : IDL.Func(
      [],
      [
        IDL.Record({
          'brands' : IDL.Vec(Brand),
          'videos' : IDL.Vec(PortfolioVideo),
        }),
      ],
      ['query'],
    ),
  'seedData' : IDL.Func([], [], []),
  'submitContactEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'toggleBrandPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleFAQPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'togglePricingPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleServicePublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleTestimonialPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleVideoPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateBrandPartner' : IDL.Func([IDL.Nat, BrandInput], [], []),
  'updateOfficeProfile' : IDL.Func([OfficeProfile], [], []),
  'updatePortfolioVideo' : IDL.Func([PortfolioVideoFullInput], [], []),
  'updatePricingPlan' : IDL.Func([IDL.Nat, PricingPlanInput], [], []),
  'updateService' : IDL.Func([ServiceFullInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BrandInput = IDL.Record({
    'mapsUrl' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const FAQInput = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const VideoInput = IDL.Record({
    'title' : IDL.Text,
    'vimeoId' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const PricingPlanInput = IDL.Record({
    'planLabel' : IDL.Text,
    'note' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ServiceInput = IDL.Record({
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const TestimonialFullInput = IDL.Record({
    'id' : IDL.Nat,
    'review' : IDL.Text,
    'clientName' : IDL.Text,
    'published' : IDL.Bool,
    'company' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactEnquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const PortfolioVideo = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'vimeoId' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Brand = IDL.Record({
    'id' : IDL.Nat,
    'mapsUrl' : IDL.Text,
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const OfficeProfile = IDL.Record({
    'city' : IDL.Text,
    'mapsUrl' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FAQItem = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'published' : IDL.Bool,
    'answer' : IDL.Text,
  });
  const PricingPlan = IDL.Record({
    'id' : IDL.Nat,
    'planLabel' : IDL.Text,
    'published' : IDL.Bool,
    'note' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'published' : IDL.Bool,
    'description' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'review' : IDL.Text,
    'clientName' : IDL.Text,
    'published' : IDL.Bool,
    'company' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const PortfolioVideoFullInput = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'vimeoId' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const ServiceFullInput = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBrandPartner' : IDL.Func([BrandInput], [IDL.Nat], []),
    'addFAQItem' : IDL.Func([FAQInput], [IDL.Nat], []),
    'addPortfolioVideo' : IDL.Func([VideoInput], [IDL.Nat], []),
    'addPricingPlan' : IDL.Func([PricingPlanInput], [IDL.Nat], []),
    'addService' : IDL.Func([ServiceInput], [IDL.Nat], []),
    'addTestimonial' : IDL.Func([TestimonialFullInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContactEnquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactEnquiry)],
        ['query'],
      ),
    'getAllVideos' : IDL.Func([], [IDL.Vec(PortfolioVideo)], ['query']),
    'getBrandsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Brand)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOfficeProfile' : IDL.Func([], [OfficeProfile], ['query']),
    'getPublishedBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getPublishedFAQs' : IDL.Func([], [IDL.Vec(FAQItem)], ['query']),
    'getPublishedPricingPlans' : IDL.Func(
        [],
        [IDL.Vec(PricingPlan)],
        ['query'],
      ),
    'getPublishedServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getPublishedTestimonials' : IDL.Func(
        [],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'getPublishedVideos' : IDL.Func([], [IDL.Vec(PortfolioVideo)], ['query']),
    'getServicesAndPricing' : IDL.Func(
        [],
        [
          IDL.Record({
            'pricing' : IDL.Vec(PricingPlan),
            'services' : IDL.Vec(Service),
          }),
        ],
        ['query'],
      ),
    'getVideoById' : IDL.Func([IDL.Nat], [IDL.Opt(PortfolioVideo)], ['query']),
    'getVideosByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioVideo)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publicCombinedVideosBrands' : IDL.Func(
        [],
        [
          IDL.Record({
            'brands' : IDL.Vec(Brand),
            'videos' : IDL.Vec(PortfolioVideo),
          }),
        ],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
    'submitContactEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'toggleBrandPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleFAQPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'togglePricingPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleServicePublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleTestimonialPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleVideoPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateBrandPartner' : IDL.Func([IDL.Nat, BrandInput], [], []),
    'updateOfficeProfile' : IDL.Func([OfficeProfile], [], []),
    'updatePortfolioVideo' : IDL.Func([PortfolioVideoFullInput], [], []),
    'updatePricingPlan' : IDL.Func([IDL.Nat, PricingPlanInput], [], []),
    'updateService' : IDL.Func([ServiceFullInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };