/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VideoInput {
    title: string;
    vimeoId: string;
    description: string;
    category: string;
}
export type Time = bigint;
export interface PortfolioVideo {
    id: bigint;
    title: string;
    vimeoId: string;
    published: boolean;
    description: string;
    category: string;
}
export interface ServiceFullInput {
    id: bigint;
    title: string;
    features: Array<string>;
    description: string;
}
export interface Service {
    id: bigint;
    title: string;
    features: Array<string>;
    published: boolean;
    description: string;
}
export interface PricingPlan {
    id: bigint;
    planLabel: string;
    published: boolean;
    note: string;
    price: bigint;
}
export interface FAQInput {
    question: string;
    answer: string;
}
export interface ContactEnquiry {
    id: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface Brand {
    id: bigint;
    mapsUrl: string;
    published: boolean;
    name: string;
    description: string;
    category: string;
    location: string;
}
export interface OfficeProfile {
    city: string;
    mapsUrl: string;
    whatsapp: string;
    email: string;
    address: string;
    phone: string;
}
export interface ServiceInput {
    title: string;
    features: Array<string>;
    description: string;
}
export interface TestimonialFullInput {
    id: bigint;
    review: string;
    clientName: string;
    published: boolean;
    company: string;
    rating: bigint;
}
export interface BrandInput {
    mapsUrl: string;
    name: string;
    description: string;
    category: string;
    location: string;
}
export interface FAQItem {
    id: bigint;
    question: string;
    published: boolean;
    answer: string;
}
export interface PricingPlanInput {
    planLabel: string;
    note: string;
    price: bigint;
}
export interface PortfolioVideoFullInput {
    id: bigint;
    title: string;
    vimeoId: string;
    published: boolean;
    description: string;
    category: string;
}
export interface Testimonial {
    id: bigint;
    review: string;
    clientName: string;
    published: boolean;
    company: string;
    rating: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBrandPartner(brand: BrandInput): Promise<bigint>;
    addFAQItem(faq: FAQInput): Promise<bigint>;
    addPortfolioVideo(video: VideoInput): Promise<bigint>;
    addPricingPlan(plan: PricingPlanInput): Promise<bigint>;
    addService(service: ServiceInput): Promise<bigint>;
    addTestimonial(input: TestimonialFullInput): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllContactEnquiries(): Promise<Array<ContactEnquiry>>;
    getAllVideos(): Promise<Array<PortfolioVideo>>;
    getBrandsByCategory(category: string): Promise<Array<Brand>>;
    getCallerUserRole(): Promise<UserRole>;
    getOfficeProfile(): Promise<OfficeProfile>;
    getPublishedBrands(): Promise<Array<Brand>>;
    getPublishedFAQs(): Promise<Array<FAQItem>>;
    getPublishedPricingPlans(): Promise<Array<PricingPlan>>;
    getPublishedServices(): Promise<Array<Service>>;
    getPublishedTestimonials(): Promise<Array<Testimonial>>;
    getPublishedVideos(): Promise<Array<PortfolioVideo>>;
    getServicesAndPricing(): Promise<{
        pricing: Array<PricingPlan>;
        services: Array<Service>;
    }>;
    getVideoById(videoId: bigint): Promise<PortfolioVideo | null>;
    getVideosByCategory(category: string): Promise<Array<PortfolioVideo>>;
    isCallerAdmin(): Promise<boolean>;
    publicCombinedVideosBrands(): Promise<{
        brands: Array<Brand>;
        videos: Array<PortfolioVideo>;
    }>;
    seedData(): Promise<void>;
    submitContactEnquiry(name: string, email: string, phone: string, message: string): Promise<bigint>;
    toggleBrandPublished(brandId: bigint): Promise<boolean>;
    toggleFAQPublished(faqId: bigint): Promise<boolean>;
    togglePricingPublished(planId: bigint): Promise<boolean>;
    toggleServicePublished(serviceId: bigint): Promise<boolean>;
    toggleTestimonialPublished(testimonialId: bigint): Promise<boolean>;
    toggleVideoPublished(videoId: bigint): Promise<boolean>;
    updateBrandPartner(id: bigint, brand: BrandInput): Promise<void>;
    updateOfficeProfile(profile: OfficeProfile): Promise<void>;
    updatePortfolioVideo(video: PortfolioVideoFullInput): Promise<void>;
    updatePricingPlan(id: bigint, plan: PricingPlanInput): Promise<void>;
    updateService(service: ServiceFullInput): Promise<void>;
}
import type { PortfolioVideo as _PortfolioVideo, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBrandPartner(arg0: BrandInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBrandPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBrandPartner(arg0);
            return result;
        }
    }
    async addFAQItem(arg0: FAQInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQItem(arg0);
            return result;
        }
    }
    async addPortfolioVideo(arg0: VideoInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortfolioVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortfolioVideo(arg0);
            return result;
        }
    }
    async addPricingPlan(arg0: PricingPlanInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPricingPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPricingPlan(arg0);
            return result;
        }
    }
    async addService(arg0: ServiceInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0);
            return result;
        }
    }
    async addTestimonial(arg0: TestimonialFullInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllContactEnquiries(): Promise<Array<ContactEnquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactEnquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactEnquiries();
            return result;
        }
    }
    async getAllVideos(): Promise<Array<PortfolioVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return result;
        }
    }
    async getBrandsByCategory(arg0: string): Promise<Array<Brand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandsByCategory(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficeProfile(): Promise<OfficeProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficeProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficeProfile();
            return result;
        }
    }
    async getPublishedBrands(): Promise<Array<Brand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBrands();
            return result;
        }
    }
    async getPublishedFAQs(): Promise<Array<FAQItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedFAQs();
            return result;
        }
    }
    async getPublishedPricingPlans(): Promise<Array<PricingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPricingPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPricingPlans();
            return result;
        }
    }
    async getPublishedServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedServices();
            return result;
        }
    }
    async getPublishedTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedTestimonials();
            return result;
        }
    }
    async getPublishedVideos(): Promise<Array<PortfolioVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedVideos();
            return result;
        }
    }
    async getServicesAndPricing(): Promise<{
        pricing: Array<PricingPlan>;
        services: Array<Service>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesAndPricing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesAndPricing();
            return result;
        }
    }
    async getVideoById(arg0: bigint): Promise<PortfolioVideo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoById(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoById(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCategory(arg0: string): Promise<Array<PortfolioVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publicCombinedVideosBrands(): Promise<{
        brands: Array<Brand>;
        videos: Array<PortfolioVideo>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.publicCombinedVideosBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicCombinedVideosBrands();
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async submitContactEnquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactEnquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactEnquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async toggleBrandPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleBrandPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleBrandPublished(arg0);
            return result;
        }
    }
    async toggleFAQPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFAQPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFAQPublished(arg0);
            return result;
        }
    }
    async togglePricingPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePricingPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePricingPublished(arg0);
            return result;
        }
    }
    async toggleServicePublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleServicePublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleServicePublished(arg0);
            return result;
        }
    }
    async toggleTestimonialPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTestimonialPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTestimonialPublished(arg0);
            return result;
        }
    }
    async toggleVideoPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleVideoPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleVideoPublished(arg0);
            return result;
        }
    }
    async updateBrandPartner(arg0: bigint, arg1: BrandInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBrandPartner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBrandPartner(arg0, arg1);
            return result;
        }
    }
    async updateOfficeProfile(arg0: OfficeProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOfficeProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOfficeProfile(arg0);
            return result;
        }
    }
    async updatePortfolioVideo(arg0: PortfolioVideoFullInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePortfolioVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePortfolioVideo(arg0);
            return result;
        }
    }
    async updatePricingPlan(arg0: bigint, arg1: PricingPlanInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePricingPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePricingPlan(arg0, arg1);
            return result;
        }
    }
    async updateService(arg0: ServiceFullInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PortfolioVideo]): PortfolioVideo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
