/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface VideoInput {
    title: string;
    vimeoId: string;
    description: string;
    category: string;
}
export interface Testimonial {
    id: bigint;
    review: string;
    clientName: string;
    published: boolean;
    company: string;
    rating: bigint;
}
export type Time = bigint;
export interface MonthlyPackage {
    videoCount: bigint;
    description: string;
    enabled: boolean;
    price: bigint;
}
export interface PortfolioVideo {
    id: bigint;
    title: string;
    vimeoId: string;
    published: boolean;
    description: string;
    category: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FullPricingPlan {
    id: bigint;
    hasSeasonOffer: boolean;
    videoCount: bigint;
    name: string;
    offerDescription: string;
    deliveryDays: bigint;
    enabled: boolean;
    offerPrice: bigint;
    price: bigint;
    planTypeBadge: string;
    services: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PricingPlan {
    id: bigint;
    planLabel: string;
    published: boolean;
    note: string;
    price: bigint;
}
export interface PageSection {
    id: string;
    description: string;
    heading: string;
    imageUrl: string;
    visible: boolean;
}
export interface FAQInput {
    question: string;
    answer: string;
}
export interface Brand {
    id: bigint;
    mapsUrl: string;
    published: boolean;
    name: string;
    description: string;
    category: string;
    location: string;
}
export interface SliderRates {
    content: bigint;
    editing: bigint;
    other: bigint;
    videography: bigint;
}
export interface ServiceInput {
    title: string;
    features: Array<string>;
    description: string;
}
export interface TestimonialFullInput {
    id: bigint;
    review: string;
    clientName: string;
    published: boolean;
    company: string;
    rating: bigint;
}
export interface PageContent {
    heroSubtitle: string;
    sections: Array<PageSection>;
    heroTitle: string;
    heroBackgroundImage: string;
    pageId: string;
}
export interface FAQItem {
    id: bigint;
    question: string;
    published: boolean;
    answer: string;
}
export interface SiteStats {
    videosDelivered: bigint;
    happyClients: bigint;
    viewsGenerated: bigint;
}
export interface ServiceFullInput {
    id: bigint;
    title: string;
    features: Array<string>;
    description: string;
}
export interface Service {
    id: bigint;
    title: string;
    features: Array<string>;
    published: boolean;
    description: string;
}
export interface PresetPackage {
    id: bigint;
    features: Array<string>;
    name: string;
    deliveryDays: bigint;
    enabled: boolean;
    price: bigint;
}
export interface ContactEnquiry {
    id: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface ReelPricing {
    editingContentCamera: bigint;
    editingCamera: bigint;
    editingOnly: bigint;
}
export interface OfficeProfile {
    city: string;
    mapsUrl: string;
    whatsapp: string;
    email: string;
    address: string;
    phone: string;
}
export interface BrandInput {
    mapsUrl: string;
    name: string;
    description: string;
    category: string;
    location: string;
}
export interface FullPricingPlanInput {
    hasSeasonOffer: boolean;
    videoCount: bigint;
    name: string;
    offerDescription: string;
    deliveryDays: bigint;
    enabled: boolean;
    offerPrice: bigint;
    price: bigint;
    planTypeBadge: string;
    services: Array<string>;
}
export interface SeasonOfferSettings {
    title: string;
    endDate: string;
    postOfferMessage: string;
    discountAmount: bigint;
    applicablePlanIds: Array<bigint>;
    offerMessage: string;
    postOfferWindowDays: bigint;
    badgeColor: string;
    startDate: string;
}
export interface PricingPlanInput {
    planLabel: string;
    note: string;
    price: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PortfolioVideoFullInput {
    id: bigint;
    title: string;
    vimeoId: string;
    published: boolean;
    description: string;
    category: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBrandPartner(brand: BrandInput): Promise<bigint>;
    addFAQItem(faq: FAQInput): Promise<bigint>;
    addFullPricingPlan(input: FullPricingPlanInput): Promise<bigint>;
    addPortfolioVideo(video: VideoInput): Promise<bigint>;
    addPricingPlan(plan: PricingPlanInput): Promise<bigint>;
    addService(service: ServiceInput): Promise<bigint>;
    addTestimonial(input: TestimonialFullInput): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBrandPartner(brandId: bigint): Promise<void>;
    deleteFAQItem(faqId: bigint): Promise<void>;
    deleteFullPricingPlan(planId: bigint): Promise<void>;
    deletePortfolioVideo(videoId: bigint): Promise<void>;
    deleteTestimonial(testimonialId: bigint): Promise<void>;
    fullPricingSeed(): Promise<void>;
    getAllBrands(): Promise<Array<Brand>>;
    getAllContactEnquiries(): Promise<Array<ContactEnquiry>>;
    getAllFAQs(): Promise<Array<FAQItem>>;
    getAllFullPricingPlans(): Promise<Array<FullPricingPlan>>;
    getAllPageContent(): Promise<Array<[string, PageContent]>>;
    getAllPresetPackages(): Promise<Array<PresetPackage>>;
    getAllPricingPlans(): Promise<Array<PricingPlan>>;
    getAllServices(): Promise<Array<Service>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getAllVideos(): Promise<Array<PortfolioVideo>>;
    getBrandsByCategory(category: string): Promise<Array<Brand>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEnabledFullPricingPlans(): Promise<Array<FullPricingPlan>>;
    getMonthlyPackage(): Promise<MonthlyPackage>;
    getOfficeProfile(): Promise<OfficeProfile>;
    getPageContent(pageId: string): Promise<PageContent | null>;
    getPresetPackages(): Promise<Array<PresetPackage>>;
    getPublishedBrands(): Promise<Array<Brand>>;
    getPublishedFAQs(): Promise<Array<FAQItem>>;
    getPublishedPricingPlans(): Promise<Array<PricingPlan>>;
    getPublishedServices(): Promise<Array<Service>>;
    getPublishedTestimonials(): Promise<Array<Testimonial>>;
    getPublishedVideos(): Promise<Array<PortfolioVideo>>;
    getReelPricing(): Promise<ReelPricing>;
    getSeasonOfferSettings(): Promise<SeasonOfferSettings>;
    getServicesAndPricing(): Promise<{
        pricing: Array<PricingPlan>;
        services: Array<Service>;
    }>;
    getSiteStats(): Promise<SiteStats>;
    getSliderRates(): Promise<SliderRates>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoById(videoId: bigint): Promise<PortfolioVideo | null>;
    getVideosByCategory(category: string): Promise<Array<PortfolioVideo>>;
    isCallerAdmin(): Promise<boolean>;
    publicCombinedVideosBrands(): Promise<{
        brands: Array<Brand>;
        videos: Array<PortfolioVideo>;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedData(): Promise<void>;
    seedPageContent(): Promise<void>;
    submitContactEnquiry(name: string, email: string, phone: string, message: string, selectedPlan: string): Promise<bigint>;
    toggleBrandPublished(brandId: bigint): Promise<boolean>;
    toggleFAQPublished(faqId: bigint): Promise<boolean>;
    toggleFullPricingPlanEnabled(planId: bigint): Promise<boolean>;
    togglePricingPublished(planId: bigint): Promise<boolean>;
    toggleServicePublished(serviceId: bigint): Promise<boolean>;
    toggleTestimonialPublished(testimonialId: bigint): Promise<boolean>;
    toggleVideoPublished(videoId: bigint): Promise<boolean>;
    updateBrandPartner(id: bigint, brand: BrandInput): Promise<void>;
    updateFullPricingPlan(id: bigint, input: FullPricingPlanInput): Promise<void>;
    updateMonthlyPackage(pkg: MonthlyPackage): Promise<void>;
    updateOfficeProfile(profile: OfficeProfile): Promise<void>;
    updatePageContent(pageId: string, content: PageContent): Promise<void>;
    updatePortfolioVideo(video: PortfolioVideoFullInput): Promise<void>;
    updatePresetPackage(pkg: PresetPackage): Promise<void>;
    updatePricingPlan(id: bigint, plan: PricingPlanInput): Promise<void>;
    updateReelPricing(pricing: ReelPricing): Promise<void>;
    updateSeasonOfferSettings(settings: SeasonOfferSettings): Promise<void>;
    updateService(service: ServiceFullInput): Promise<void>;
    updateSiteStats(stats: SiteStats): Promise<void>;
    updateSliderRates(rates: SliderRates): Promise<void>;
}
import type { PageContent as _PageContent, PortfolioVideo as _PortfolioVideo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBrandPartner(arg0: BrandInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBrandPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBrandPartner(arg0);
            return result;
        }
    }
    async addFAQItem(arg0: FAQInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQItem(arg0);
            return result;
        }
    }
    async addFullPricingPlan(arg0: FullPricingPlanInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFullPricingPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFullPricingPlan(arg0);
            return result;
        }
    }
    async addPortfolioVideo(arg0: VideoInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortfolioVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortfolioVideo(arg0);
            return result;
        }
    }
    async addPricingPlan(arg0: PricingPlanInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPricingPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPricingPlan(arg0);
            return result;
        }
    }
    async addService(arg0: ServiceInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0);
            return result;
        }
    }
    async addTestimonial(arg0: TestimonialFullInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBrandPartner(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBrandPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBrandPartner(arg0);
            return result;
        }
    }
    async deleteFAQItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFAQItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFAQItem(arg0);
            return result;
        }
    }
    async deleteFullPricingPlan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFullPricingPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFullPricingPlan(arg0);
            return result;
        }
    }
    async deletePortfolioVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolioVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolioVideo(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async fullPricingSeed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fullPricingSeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fullPricingSeed();
            return result;
        }
    }
    async getAllBrands(): Promise<Array<Brand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBrands();
            return result;
        }
    }
    async getAllContactEnquiries(): Promise<Array<ContactEnquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactEnquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactEnquiries();
            return result;
        }
    }
    async getAllFAQs(): Promise<Array<FAQItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFAQs();
            return result;
        }
    }
    async getAllFullPricingPlans(): Promise<Array<FullPricingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFullPricingPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFullPricingPlans();
            return result;
        }
    }
    async getAllPageContent(): Promise<Array<[string, PageContent]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPageContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPageContent();
            return result;
        }
    }
    async getAllPresetPackages(): Promise<Array<PresetPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPresetPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPresetPackages();
            return result;
        }
    }
    async getAllPricingPlans(): Promise<Array<PricingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPricingPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPricingPlans();
            return result;
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return result;
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
    async getAllVideos(): Promise<Array<PortfolioVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return result;
        }
    }
    async getBrandsByCategory(arg0: string): Promise<Array<Brand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandsByCategory(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnabledFullPricingPlans(): Promise<Array<FullPricingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnabledFullPricingPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnabledFullPricingPlans();
            return result;
        }
    }
    async getMonthlyPackage(): Promise<MonthlyPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyPackage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyPackage();
            return result;
        }
    }
    async getOfficeProfile(): Promise<OfficeProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficeProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficeProfile();
            return result;
        }
    }
    async getPageContent(arg0: string): Promise<PageContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPageContent(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPageContent(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPresetPackages(): Promise<Array<PresetPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresetPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresetPackages();
            return result;
        }
    }
    async getPublishedBrands(): Promise<Array<Brand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBrands();
            return result;
        }
    }
    async getPublishedFAQs(): Promise<Array<FAQItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedFAQs();
            return result;
        }
    }
    async getPublishedPricingPlans(): Promise<Array<PricingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPricingPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPricingPlans();
            return result;
        }
    }
    async getPublishedServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedServices();
            return result;
        }
    }
    async getPublishedTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedTestimonials();
            return result;
        }
    }
    async getPublishedVideos(): Promise<Array<PortfolioVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedVideos();
            return result;
        }
    }
    async getReelPricing(): Promise<ReelPricing> {
        if (this.processError) {
            try {
                const result = await this.actor.getReelPricing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReelPricing();
            return result;
        }
    }
    async getSeasonOfferSettings(): Promise<SeasonOfferSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeasonOfferSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeasonOfferSettings();
            return result;
        }
    }
    async getServicesAndPricing(): Promise<{
        pricing: Array<PricingPlan>;
        services: Array<Service>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesAndPricing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesAndPricing();
            return result;
        }
    }
    async getSiteStats(): Promise<SiteStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteStats();
            return result;
        }
    }
    async getSliderRates(): Promise<SliderRates> {
        if (this.processError) {
            try {
                const result = await this.actor.getSliderRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSliderRates();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoById(arg0: bigint): Promise<PortfolioVideo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoById(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoById(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCategory(arg0: string): Promise<Array<PortfolioVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publicCombinedVideosBrands(): Promise<{
        brands: Array<Brand>;
        videos: Array<PortfolioVideo>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.publicCombinedVideosBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicCombinedVideosBrands();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async seedPageContent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedPageContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedPageContent();
            return result;
        }
    }
    async submitContactEnquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactEnquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactEnquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async toggleBrandPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleBrandPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleBrandPublished(arg0);
            return result;
        }
    }
    async toggleFAQPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFAQPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFAQPublished(arg0);
            return result;
        }
    }
    async toggleFullPricingPlanEnabled(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFullPricingPlanEnabled(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFullPricingPlanEnabled(arg0);
            return result;
        }
    }
    async togglePricingPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePricingPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePricingPublished(arg0);
            return result;
        }
    }
    async toggleServicePublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleServicePublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleServicePublished(arg0);
            return result;
        }
    }
    async toggleTestimonialPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTestimonialPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTestimonialPublished(arg0);
            return result;
        }
    }
    async toggleVideoPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleVideoPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleVideoPublished(arg0);
            return result;
        }
    }
    async updateBrandPartner(arg0: bigint, arg1: BrandInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBrandPartner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBrandPartner(arg0, arg1);
            return result;
        }
    }
    async updateFullPricingPlan(arg0: bigint, arg1: FullPricingPlanInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFullPricingPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFullPricingPlan(arg0, arg1);
            return result;
        }
    }
    async updateMonthlyPackage(arg0: MonthlyPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMonthlyPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMonthlyPackage(arg0);
            return result;
        }
    }
    async updateOfficeProfile(arg0: OfficeProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOfficeProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOfficeProfile(arg0);
            return result;
        }
    }
    async updatePageContent(arg0: string, arg1: PageContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePageContent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePageContent(arg0, arg1);
            return result;
        }
    }
    async updatePortfolioVideo(arg0: PortfolioVideoFullInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePortfolioVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePortfolioVideo(arg0);
            return result;
        }
    }
    async updatePresetPackage(arg0: PresetPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePresetPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePresetPackage(arg0);
            return result;
        }
    }
    async updatePricingPlan(arg0: bigint, arg1: PricingPlanInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePricingPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePricingPlan(arg0, arg1);
            return result;
        }
    }
    async updateReelPricing(arg0: ReelPricing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReelPricing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReelPricing(arg0);
            return result;
        }
    }
    async updateSeasonOfferSettings(arg0: SeasonOfferSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSeasonOfferSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSeasonOfferSettings(arg0);
            return result;
        }
    }
    async updateService(arg0: ServiceFullInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0);
            return result;
        }
    }
    async updateSiteStats(arg0: SiteStats): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteStats(arg0);
            return result;
        }
    }
    async updateSliderRates(arg0: SliderRates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSliderRates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSliderRates(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PageContent]): PageContent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PortfolioVideo]): PortfolioVideo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
